language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run swagger:validate
after_success:
  - yarn run swagger:gen_docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "api_docs"
  target_branch: "gh-pages"
  on:
    branch: master
